"""
LLM-as-a-Judge: оценка усвоения коллективного стиля Telegram-комментариев.
Синхронная версия на OpenAI SDK (OpenRouter).
"""

import json
import random
import math
import time
from collections import defaultdict, Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
from dotenv import load_dotenv
import os

load_dotenv()
from openai import OpenAI


EVAL_PATH     = "evaluating/evaluation_results.json"
POSTS_PATH    = "evaluating/eval_posts.json"
COMMENTS_PATH = "evaluating/id_comments.json"
API_KEY       = os.getenv("API_KEY")
MODEL         = "openai/gpt-5-nano"
RUNS          = 1
OUTPUT_PATH   = "evaluating/judge_results.json"
STATS_PATH    = "evaluating/judge_stats.json"
SEED          = 42
CONCURRENCY   = 50

EVAL_RESULTS_CONFIGS = [
    "rugpt3_base",
    "qwen_base",
    "rugpt3_ft_ep1",
    "rugpt3_ft_ep3",
    "qwen_ft_ep2",
    "qwen_ft_ep3",
]

QWEN_FILES = [
    "evaluating/qwen_lora_r8.json",
    "evaluating/qwen_lora_r16.json",
    "evaluating/qwen_lora_r32.json",
    "evaluating/qwen_lora_ffn.json",
    "evaluating/qwen_lora_fan.json",
    "evaluating/qwen_ia3.json",
]


client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=API_KEY,
)


SYSTEM_PROMPT = """You are an expert evaluator of Russian-language Telegram comments.

You will be shown a Telegram post followed by several comments (from 2 to 4).
Exactly ONE comment was generated by an AI model; the rest are real human comments from the channel's community.
All the emojis were presented in text form.
Your task: identify which comment is AI-generated.


Respond ONLY with a valid JSON object (no markdown, no extra text):
{"answer": <int, 1-indexed comment number>, "confidence": <float 0.0-1.0>, "reasoning": "<brief explanation in Russian, 1-2 sentences>"}"""


def build_user_prompt(post: str, comments: list[str]) -> str:
    lines = [f"Пост: {post}", ""]
    for i, c in enumerate(comments, 1):
        lines.append(f"Комментарий {i}: {c}")
    return "\n".join(lines)


def call_llm(
    post: str,
    comments: list[str],
    model: str = MODEL,
    temperature: float = 0.3,
    max_retries: int = 3,
) -> dict | None:
    for attempt in range(max_retries):
        text = ""
        try:
            response = client.chat.completions.create(
                model=model,
                temperature=temperature,
                max_tokens=1000,
                messages=[
                    {"role": "system", "content": SYSTEM_PROMPT},
                    {"role": "user", "content": build_user_prompt(post, comments)},
                ],
                extra_body={"reasoning": {"effort": "low", "exclude": True}},
            )

            message = response.choices[0].message
            text = message.content.strip()

            if text.startswith("```"):
                text = text.split("\n", 1)[1] if "\n" in text else text[3:]
                text = text.rsplit("```", 1)[0]

            return json.loads(text.strip())

        except json.JSONDecodeError as e:
            print(f"  JSON parse error (attempt {attempt+1}): {e}")
            print(f"  Raw: {text[:200]}")
            if attempt < max_retries - 1:
                time.sleep(1)

        except Exception as e:
            err_str = str(e)
            if "429" in err_str or "rate" in err_str.lower():
                wait = 2 ** (attempt + 1)
                print(f"  Rate limited, waiting {wait}s...")
                time.sleep(wait)
                continue

            print(f"  Error (attempt {attempt+1}/{max_retries}): {e}")
            if attempt < max_retries - 1:
                time.sleep(2 ** attempt)

    return None


def build_examples(
    config_name: str,
    all_generated: list[str],
    eval_indices: list[int],
    eval_posts: list[str],
    real_comments: dict[str, list[str]],
    seed: int = 42,
) -> list[dict]:
    rng = random.Random(seed)
    examples = []

    for i, (post_id, post_text, generated) in enumerate(
        zip(eval_indices, eval_posts, all_generated)
    ):
        pid_str = str(post_id)
        if pid_str not in real_comments:
            continue

        reals = [c.strip() for c in real_comments[pid_str] if c.strip()]
        gen = generated.strip()

        if not gen or len(gen) < 5 or not reals:
            continue

        gen_clean = gen.split("\n\n")[0].strip()
        if len(gen_clean) >= 10:
            gen = gen_clean

        all_comments = list(reals)
        insert_pos = rng.randint(0, len(all_comments))
        all_comments.insert(insert_pos, gen)

        examples.append({
            "post": post_text,
            "post_id": post_id,
            "eval_index": i,
            "comments": all_comments,
            "gt_position": insert_pos + 1,
            "n_total": len(all_comments),
            "n_real": len(reals),
            "generated_text": gen,
        })

    return examples


def evaluate_single(
    ex: dict,
    idx: int,
    total: int,
    config_name: str,
    run_id: int,
) -> dict | None:
    resp = call_llm(ex["post"], ex["comments"])

    if resp is None:
        print(
            f"  [{config_name}] run={run_id} {idx+1}/{total} "
            f"pid={ex['post_id']} FAILED"
        )
        return None

    answer = resp.get("answer")
    correct = answer == ex["gt_position"]
    print(
        f"  [{config_name}] run={run_id} {idx+1}/{total} "
        f"pid={ex['post_id']} ({ex['n_total']} comments) "
        f"ans={answer} gt={ex['gt_position']} "
        f"{'OK' if correct else 'NO'} conf={resp.get('confidence', '?')}"
    )

    return {
        "config": config_name,
        "run": run_id,
        "post_id": ex["post_id"],
        "eval_index": ex["eval_index"],
        "n_total": ex["n_total"],
        "n_real": ex["n_real"],
        "gt_position": ex["gt_position"],
        "llm_answer": answer,
        "correct": correct,
        "confidence": resp.get("confidence"),
        "reasoning": resp.get("reasoning", ""),
        "generated_preview": ex["generated_text"][:120],
    }


def evaluate_config(
    config_name: str,
    examples: list[dict],
    run_id: int = 0,
) -> list[dict]:
    results = []

    with ThreadPoolExecutor(max_workers=CONCURRENCY) as pool:
        futures = {
            pool.submit(
                evaluate_single, ex, i, len(examples), config_name, run_id
            ): i
            for i, ex in enumerate(examples)
        }

        for future in as_completed(futures):
            result = future.result()
            if result is not None:
                results.append(result)

    return results


def print_stats(all_results: list[dict]):
    stats = defaultdict(lambda: {
        "correct": 0, "total": 0, "baselines": [],
        "confidences_correct": [], "confidences_wrong": [],
    })

    for r in all_results:
        key = r["config"]
        s = stats[key]
        s["total"] += 1
        if r["correct"]:
            s["correct"] += 1
            if r["confidence"] is not None:
                s["confidences_correct"].append(r["confidence"])
        else:
            if r["confidence"] is not None:
                s["confidences_wrong"].append(r["confidence"])
        s["baselines"].append(1.0 / r["n_total"])

    print("\n" + "=" * 95)
    print(
        f"{'Конфиг':<25} {'ACC':>6} {'Base':>6} {'D':>7} {'N':>4}  "
        f"{'95% CI':<14} {'Conf+':>6} {'Conf-':>6}  Вердикт"
    )
    print("-" * 95)

    rows = []
    for config in sorted(stats.keys()):
        s = stats[config]
        acc = s["correct"] / s["total"]
        baseline = sum(s["baselines"]) / len(s["baselines"])
        n = s["total"]
        delta = acc - baseline

        se = math.sqrt(acc * (1 - acc) / n) if n > 1 else 0
        ci_lo = max(0, acc - 1.96 * se)
        ci_hi = min(1, acc + 1.96 * se)

        conf_c = (
            sum(s["confidences_correct"]) / len(s["confidences_correct"])
            if s["confidences_correct"] else float("nan")
        )
        conf_w = (
            sum(s["confidences_wrong"]) / len(s["confidences_wrong"])
            if s["confidences_wrong"] else float("nan")
        )

        if ci_hi <= baseline + 0.02:
            verdict = "Не отличает"
        elif ci_lo <= baseline:
            verdict = "Неопределённо"
        elif acc < baseline + 0.15:
            verdict = "Слабо отличает"
        else:
            verdict = "Отличает"

        rows.append((config, acc, baseline, delta, n, ci_lo, ci_hi,
                      conf_c, conf_w, verdict))

    rows.sort(key=lambda r: r[3])

    for config, acc, baseline, delta, n, ci_lo, ci_hi, conf_c, conf_w, verdict in rows:
        conf_c_s = f"{conf_c:.2f}" if not math.isnan(conf_c) else "  -- "
        conf_w_s = f"{conf_w:.2f}" if not math.isnan(conf_w) else "  -- "
        print(
            f"{config:<25} {acc:>5.1%} {baseline:>5.1%} {delta:>+6.1%} "
            f"{n:>4}  [{ci_lo:.1%}-{ci_hi:.1%}]  "
            f"{conf_c_s:>6} {conf_w_s:>6}  {verdict}"
        )

    print("=" * 95)
    print("ACC  = доля верных идентификаций судьёй (ниже -> модель лучше прячется)")
    print("Base = случайное угадывание (25-50% в зависимости от числа комментариев)")
    print("D    = ACC - Base (отрицательное = модель прячется лучше случайного)")
    print("Conf+/- = средняя уверенность судьи при верных/ошибочных ответах")
    print()


def iter_configs(eval_data: dict, posts_data: dict):
    """Возвращает (config_name, all_generated, eval_indices, eval_posts)."""
    global_indices = posts_data["eval_indices"]
    global_posts = posts_data["eval_posts"]

    for name in EVAL_RESULTS_CONFIGS:
        cfg = eval_data.get(name)
        if not cfg or "all_generated" not in cfg:
            print(f"Пропуск {name}: нет в {EVAL_PATH}")
            continue
        if len(cfg["all_generated"]) != len(global_indices):
            print(
                f"Пропуск {name}: all_generated ({len(cfg['all_generated'])}) "
                f"!= eval_indices ({len(global_indices)})"
            )
            continue
        yield name, cfg["all_generated"], global_indices, global_posts

    for path in QWEN_FILES:
        try:
            with open(path, "r", encoding="utf-8") as f:
                d = json.load(f)
        except FileNotFoundError:
            print(f"Пропуск {path}: файл не найден")
            continue

        file_indices = d.get("eval_indices")
        file_posts = d.get("test_posts")
        epochs = d.get("epochs", {})
        if not file_indices or not file_posts or not epochs:
            print(f"Пропуск {path}: нет eval_indices/test_posts/epochs")
            continue

        stem = os.path.basename(path).rsplit(".", 1)[0]
        for ep_key in sorted(epochs, key=lambda k: int(k.split("_")[-1])):
            gens = epochs[ep_key].get("all_generated")
            if not gens or len(gens) != len(file_indices):
                print(
                    f"Пропуск {stem}/{ep_key}: all_generated отсутствует "
                    f"или его длина не совпадает с eval_indices"
                )
                continue
            ep_n = ep_key.split("_")[-1]
            yield f"{stem}_ep{ep_n}", gens, file_indices, file_posts


def save_stats(all_results: list[dict], path: str = STATS_PATH):
    by_cfg = defaultdict(lambda: {"correct": 0, "total": 0})
    for r in all_results:
        s = by_cfg[r["config"]]
        s["total"] += 1
        if r["correct"]:
            s["correct"] += 1

    accuracy_per_config = {
        cfg: {
            "accuracy": s["correct"] / s["total"] if s["total"] else 0.0,
            "correct": s["correct"],
            "total": s["total"],
        }
        for cfg, s in by_cfg.items()
    }

    post_counter: Counter = Counter()
    for r in all_results:
        if not r["correct"]:
            post_counter[r["post_id"]] += 1

    post_scores = {str(pid): cnt for pid, cnt in post_counter.most_common()}

    payload = {
        "accuracy_per_config": accuracy_per_config,
        "post_scores": post_scores,
    }
    with open(path, "w", encoding="utf-8") as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    print(f"\nСтатистика -> {path}")

    print("\nТоп постов по 'спрятанности' (число конфигов, где судья ошибся):")
    for pid, cnt in post_counter.most_common(25):
        print(f"  {pid}: {cnt}")


def run_evaluation():
    with open(EVAL_PATH, "r", encoding="utf-8") as f:
        eval_data = json.load(f)
    with open(POSTS_PATH, "r", encoding="utf-8") as f:
        posts_data = json.load(f)
    with open(COMMENTS_PATH, "r", encoding="utf-8") as f:
        real_comments = json.load(f)

    config_specs = list(iter_configs(eval_data, posts_data))

    n_with_comments = sum(
        1 for pid in posts_data["eval_indices"] if str(pid) in real_comments
    )
    print(f"Постов в глобальной выборке: {len(posts_data['eval_indices'])}")
    print(f"  из них с реальными комментариями: {n_with_comments}")
    print(f"Конфигов к оценке: {len(config_specs)}")
    print(f"Модель-судья: {MODEL}")
    print(f"Прогонов: {RUNS}, параллельных потоков: {CONCURRENCY}")

    est_calls = n_with_comments * len(config_specs) * RUNS
    print(f"Примерно запросов: {est_calls}\n")

    all_results = []
    for config_name, all_generated, eval_indices, eval_posts in config_specs:
        for run in range(RUNS):
            seed = SEED + run * 1000
            examples = build_examples(
                config_name, all_generated, eval_indices,
                eval_posts, real_comments, seed=seed,
            )

            print(
                f"\n{config_name} (run {run+1}/{RUNS}, "
                f"{len(examples)} примеров)"
            )

            results = evaluate_config(config_name, examples, run_id=run)
            all_results.extend(results)

    with open(OUTPUT_PATH, "w", encoding="utf-8") as f:
        json.dump(all_results, f, ensure_ascii=False, indent=2)
    print(f"\nРезультаты -> {OUTPUT_PATH}")

    if all_results:
        print_stats(all_results)
        save_stats(all_results)
    else:
        print("Нет результатов.")

    return all_results


results = run_evaluation()
